syntax = "proto3";


option csharp_namespace = "ECommerceGRPC.OrderService";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

package order;

// Servicio de órdenes con gRPC
service OrderService {
  rpc CreateOrder (CreateOrderRequest) returns (OrderResponse);
  rpc GetOrder (GetOrderRequest) returns (OrderResponse);
  rpc UpdateOrderStatus (UpdateOrderStatusRequest) returns (OrderResponse);
  rpc ListOrders (ListOrdersRequest) returns (ListOrdersResponse);
  rpc CancelOrder (CancelOrderRequest) returns (OrderResponse);
}

// Mensajes de petición
message CreateOrderRequest {
  int32 user_id = 1;
  string shipping_address = 2;
  repeated OrderItemRequest items = 3;
}

message GetOrderRequest {
  int32 id = 1;
}

message UpdateOrderStatusRequest {
  int32 id = 1;
  string status = 2;
  string payment_transaction_id = 3;
}

message ListOrdersRequest {
  int32 user_id = 1;
  int32 page = 2;
  int32 page_size = 3;
}

message CancelOrderRequest {
  int32 id = 1;
}

message OrderItemRequest {
  int32 product_id = 1;
  string product_name = 2;
  int32 quantity = 3;
  string unit_price = 4; // decimal como string
}

// Mensajes de respuesta
message OrderResponse {
  int32 id = 1;
  int32 user_id = 2;
  google.protobuf.Timestamp order_date = 3;
  string status = 4;
  string total_amount = 5; // decimal como string
  string shipping_address = 6;
  repeated OrderItemMessage items = 7;
  google.protobuf.StringValue payment_transaction_id = 8;
  google.protobuf.Timestamp updated_at = 9;
}

message OrderItemMessage {
  int32 id = 1;
  int32 order_id = 2;
  int32 product_id = 3;
  string product_name = 4;
  int32 quantity = 5;
  string unit_price = 6; // decimal como string
  string subtotal = 7; // decimal como string
}

message ListOrdersResponse {
  repeated OrderResponse orders = 1;
  int32 total_count = 2;
  int32 page = 3;
  int32 page_size = 4;
}