syntax = "proto3";

option csharp_namespace = "ECommerceGRPC.OrderService";

package orderservice;

service OrderService {

	rpc GetOrders(GetOrdersRequest)   returns (stream OrderResponse);

	rpc GetOrderById(GetOrderByIdRequest) returns (OrderResponse) ;

	rpc GetOrderByUser(GetOrderByUserRequest) returns (stream OrderResponse);

	rpc CreateOrder(CreateOrderRequest) returns (OrderResponse);

	rpc UpdateOrderStatus(UpdateOrderStatusRequest) returns (OrderResponse);
 
	rpc CancelOrder(UpdateOrderStatusRequest) returns (OrderResponse);

}

message GetOrdersRequest {
	 int32 page_number = 1;      // Número de página (default: 1)
     int32 page_size = 2;         // Tamaño de página (default: 10)     
}

message GetOrderByIdRequest {
	int32 id = 1;
}


message GetOrderByUserRequest {
	int32 user_id = 1;
}

message CreateOrderRequest {
	int32 user_id = 1 ;
    double total_amount = 2;
    string shipping_address = 3 ;
}

message UpdateOrderStatusRequest {
	int32 id = 1;
    string status = 2 ;
}

message OrdenItemResponse {
	int32 id = 1 ;
    int32 product_id  = 2 ;
    string product_name = 3 ; 
    int32 quantity = 4 ;
    double unit_price = 5 ;
  
}


message OrderResponse {
	 int32 id = 1 ;
     int32 user_id  = 2 ;
     string order_date =  3 ;
     string status  = 4 ;
     double total_amount = 5 ;
     string shipping_address  = 6 ; 
     repeated OrdenItemResponse items = 7;   
     string payment_transaction_id = 8;
     string updated_at = 9;

}
